apiVersion: v1
kind: Service
metadata:
  name: teste-prod
spec:
  ports:
  - protocol: TCP
    targetPort: 3000
    port: 3000
    nodePort: 30200
  selector:
      app: teste-prod
  type: LoadBalancer
  